# Generated by Django 6.0.2 on 2026-09-30 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Номер телефона')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО Заказчика')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('company', models.CharField(blank=True, max_length=200, null=True, verbose_name='Организация / Бюро / Объект')),
                ('access_pin', models.CharField(default='1234', max_length=10, verbose_name='Код быстрого доступа / ПИН')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Служебные заметки Натальи / CRM')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Клиентский профиль',
                'verbose_name_plural': 'Клиентская база (Личные кабинеты)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Премиальный жилой интерьер', max_length=200, verbose_name='Название объекта')),
                ('contract_number', models.CharField(blank=True, default='GB-2026/09-14', max_length=50, verbose_name='Номер договора')),
                ('address', models.CharField(blank=True, default='Москва, Центр', max_length=255, verbose_name='Адрес объекта')),
                ('total_area', models.CharField(default='240 м²', max_length=50, verbose_name='Площадь помещений')),
                ('total_amount', models.DecimalField(decimal_places=2, default=850000, max_digits=12, verbose_name='Сумма по смете (₽)')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=425000, max_digits=12, verbose_name='Оплачено заказчиком (₽)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала работ')),
                ('estimated_completion', models.DateField(blank=True, null=True, verbose_name='Планируемая сдача')),
                ('lead_artisan', models.CharField(default='Александр Попыкин', max_length=150, verbose_name='Ведущий мастер / Технолог')),
                ('artisan_phone', models.CharField(default='+7 (495) 890-44-22', max_length=50, verbose_name='Телефон технолога объекта')),
                ('status', models.CharField(choices=[('active', 'В активной работе'), ('review', 'Приемка и технический контроль'), ('completed', 'Объект сдан (на 5-летней гарантии)')], default='active', max_length=30, verbose_name='Статус объекта')),
                ('progress_percent', models.PositiveIntegerField(default=65, verbose_name='Общий прогресс (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания карточки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portal.clientaccount', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Объект заказчика',
                'verbose_name_plural': 'Объекты в работе (Трекер)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название документа')),
                ('doc_type', models.CharField(choices=[('contract', 'Договор подряда'), ('estimate', 'Смета и спецификация материалов'), ('act', 'Акт скрытых работ / КС-2'), ('warranty', 'Официальный сертификат 5 лет гарантии'), ('tech', 'Технологическая карта нанесения'), ('other', 'Прочие документы')], default='contract', max_length=50, verbose_name='Тип документа')),
                ('file', models.FileField(blank=True, null=True, upload_to='portal/docs/%Y/%m/', verbose_name='Файл (PDF/DOCX)')),
                ('external_url', models.URLField(blank=True, null=True, verbose_name='Внешняя ссылка на скачивание')),
                ('size_label', models.CharField(default='PDF, 2.4 МБ', max_length=50, verbose_name='Размер / Формат')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='portal.projectcontract', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Проектный документ',
                'verbose_name_plural': 'Проектные документы и сметы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(default=1, verbose_name='Порядок этапа')),
                ('title', models.CharField(max_length=200, verbose_name='Название этапа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Техническое описание и примечания')),
                ('status', models.CharField(choices=[('completed', 'Завершен'), ('in_progress', 'В работе сейчас'), ('pending', 'Ожидает начала')], default='pending', max_length=30, verbose_name='Статус этапа')),
                ('date_label', models.CharField(blank=True, max_length=100, null=True, verbose_name='Сроки / Дата завершения')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='portal.projectcontract', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Этап реализации',
                'verbose_name_plural': 'Этапы реализации объекта',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='StageUpdatePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portal/updates/%Y/%m/', verbose_name='Фотография со стройки/мастерской')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Или URL изображения')),
                ('caption', models.CharField(max_length=255, verbose_name='Подпись к фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='portal.projectcontract', verbose_name='Объект')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_photos', to='portal.projectstage', verbose_name='Привязка к этапу')),
            ],
            options={
                'verbose_name': 'Фотоотчет со стройки',
                'verbose_name_plural': 'Фотоотчеты со стройки (Бэкстейдж)',
                'ordering': ['-created_at'],
            },
        ),
    ]
