# Generated by Django 6.0.2 on 2026-09-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Контактное лицо')),
                ('company', models.CharField(blank=True, max_length=200, null=True, verbose_name='Компания / Предприятие / Бюро')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('object_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип объекта')),
                ('area_range', models.CharField(blank=True, max_length=100, null=True, verbose_name='Площадь объекта')),
                ('service_needed', models.CharField(blank=True, max_length=255, null=True, verbose_name='Требуемые услуги')),
                ('timeline', models.CharField(blank=True, max_length=100, null=True, verbose_name='Планируемые сроки')),
                ('estimated_cost', models.CharField(blank=True, max_length=100, null=True, verbose_name='Предварительная оценка сметы')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Комментарий заказчика / ТЗ')),
                ('source', models.CharField(choices=[('quiz', 'Интерактивный B2B-квиз'), ('sample_box', 'Заказ Sample Box для архитекторов'), ('audit_form', 'Заявка на аудит объекта'), ('art_inquiry', 'Запрос на арт-работу (Галерея)'), ('quick_call', 'Быстрый звонок / Консультация')], default='quiz', max_length=50, verbose_name='Источник лида')),
                ('status', models.CharField(choices=[('new', 'Новая заявка'), ('in_progress', 'В обработке (контакт установлен)'), ('audit_booked', 'Назначен выезд инженера на объект'), ('kp_sent', 'ТКП / Смета направлена'), ('contract', 'Заключение договора / Сделка'), ('archived', 'Архив / Нецелевой')], default='new', max_length=30, verbose_name='Статус обработки')),
                ('manager_notes', models.TextField(blank=True, null=True, verbose_name='Заметки Натальи / Менеджера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время поступления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Входящий Лид (Заявка)',
                'verbose_name_plural': 'Входящие Лиды (CRM)',
                'ordering': ['-created_at'],
            },
        ),
    ]
