# Generated by Django 6.0.2 on 2026-09-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок статьи')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг URL')),
                ('tag', models.CharField(default='Fit-Out Экспертиза', max_length=100, verbose_name='Тематический тег')),
                ('summary', models.TextField(verbose_name='Краткий анонс статьи')),
                ('content', models.TextField(verbose_name='Текст статьи (поддерживает HTML разметку)')),
                ('image_url', models.CharField(default='/static/images/hero.jpg', max_length=255, verbose_name='Превью статьи')),
                ('read_time', models.CharField(default='4 мин', max_length=50, verbose_name='Время чтения')),
                ('published_date', models.DateField(verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Статья / Публикация',
                'verbose_name_plural': 'Статьи и Блог',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название выставки / Проекта')),
                ('venue', models.CharField(max_length=150, verbose_name='Арт-пространство / Галерея')),
                ('city', models.CharField(default='Москва', max_length=100, verbose_name='Город')),
                ('year', models.PositiveIntegerField(default=2024, verbose_name='Год')),
                ('dates', models.CharField(blank=True, max_length=100, verbose_name='Даты проведения')),
                ('exhibition_type', models.CharField(default='Персональная выставка', max_length=100, verbose_name='Формат')),
                ('status', models.CharField(choices=[('upcoming', 'Предстоящая выставка'), ('current', 'Текущая экспозиция'), ('past', 'Архив / Прошедшая')], default='past', max_length=30, verbose_name='Статус')),
                ('description', models.TextField(blank=True, verbose_name='Описание проекта / Концепция')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Выставка',
                'verbose_name_plural': 'Выставочная деятельность Саши',
                'ordering': ['-year', 'order'],
            },
        ),
    ]
