# Generated by Django 6.0.2 on 2026-09-23 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_date'], 'verbose_name': 'Запись Журнала / Статья', 'verbose_name_plural': 'Журнал Мастерской (Atelier Notes)'},
        ),
        migrations.AddField(
            model_name='article',
            name='author_quote',
            field=models.TextField(blank=True, help_text='Ключевая авторская мысль для акцентного блока', null=True, verbose_name='Мысль автора / Цитата Саши'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('wip', 'Мастерская: Work in Progress (Процесс создания)'), ('surfaces', 'Архитектура & Фактуры (Fit-Out философия)'), ('ceramics', 'Интерьерная керамика & Форма'), ('exhibitions', 'Хроника признания & События'), ('expert', 'Экспертиза генподряда')], default='wip', max_length=50, verbose_name='Рубрика журнала'),
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='journal/', verbose_name='Основное фото (загрузка с диска)'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(default=True, verbose_name='Выводить на главной в Мастерской'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.CharField(default='/static/images/hero.jpg', max_length=255, verbose_name='Превью (URL или статический путь)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(verbose_name='Краткий анонс / Кураторская экспликация'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.CharField(default='Мастерская Саши Попыкина', max_length=100, verbose_name='Тематический тег'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Заголовок статьи / Эссе'),
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='journal/process/', verbose_name='Фото этапа создания')),
                ('image_url', models.CharField(blank=True, default='/static/images/art_canvas.jpg', max_length=255, verbose_name='URL фото этапа')),
                ('caption', models.CharField(blank=True, max_length=250, verbose_name='Подпись к фотографии (стадия работы / материал)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_images', to='articles.article', verbose_name='Запись журнала')),
            ],
            options={
                'verbose_name': 'Фотография процесса (WIP)',
                'verbose_name_plural': 'Галерея процесса создания',
                'ordering': ['order', 'id'],
            },
        ),
    ]
