# Generated by Django 6.0.2 on 2026-09-19 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Категория объектов',
                'verbose_name_plural': 'Категории объектов',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг URL')),
                ('client_name', models.CharField(blank=True, max_length=150, verbose_name='Заказчик / Бренд')),
                ('location', models.CharField(default='Москва', max_length=150, verbose_name='Локация / Город')),
                ('area_sqm', models.PositiveIntegerField(help_text='Например: 1850', verbose_name='Площадь, м²')),
                ('year', models.PositiveIntegerField(default=2024, verbose_name='Год реализации')),
                ('duration', models.CharField(default='3 месяца', max_length=100, verbose_name='Срок выполнения')),
                ('short_description', models.TextField(verbose_name='Краткое описание проекта')),
                ('scope_of_work', models.TextField(help_text='Например: Комплексный fit-out под ключ; Монтаж вентиляции и СКС; Авторские рельефные покрытия стен; Изготовление стола из массива дуба и латуни', verbose_name='Выполненные работы (через точку с запятой)')),
                ('image_url', models.CharField(default='/static/images/case_hotel.jpg', max_length=255, verbose_name='URL или путь к изображению')),
                ('is_featured', models.BooleanField(default=True, verbose_name='Отображать на главной')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.projectcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Объект Fit-Out (Кейс)',
                'verbose_name_plural': 'Объекты Fit-Out (Портфолио)',
                'ordering': ['order', '-year'],
            },
        ),
    ]
