# Generated by Django 6.0.2 on 2026-09-19 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название направления')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория арт-работ',
                'verbose_name_plural': 'Категории арт-работ',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название произведения')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('year', models.PositiveIntegerField(default=2024, verbose_name='Год создания')),
                ('dimensions', models.CharField(help_text='Например: 160 × 130 см или h: 42 см', max_length=100, verbose_name='Размеры')),
                ('medium', models.CharField(help_text='Например: Холст, минеральные пигменты, акрил, графит', max_length=255, verbose_name='Техника и материалы')),
                ('status', models.CharField(choices=[('available', 'Доступна к приобретению'), ('in_collection', 'В частной коллекции'), ('reserved', 'Зарезервировано')], default='available', max_length=30, verbose_name='Статус')),
                ('price', models.CharField(default='По запросу', help_text='Например: 350 000 ₽ или По запросу', max_length=100, verbose_name='Стоимость')),
                ('curator_note', models.TextField(verbose_name='Кураторская экспликация / Описание концепции')),
                ('image_url', models.CharField(default='/static/images/art_canvas.jpg', max_length=255, verbose_name='Изображение (URL или статический путь)')),
                ('is_featured', models.BooleanField(default=True, verbose_name='Показывать в избранном')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='gallery.artworkcategory', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Произведение искусства',
                'verbose_name_plural': 'Арт-Галерея (Работы Саши)',
                'ordering': ['order', '-year'],
            },
        ),
    ]
