# Generated by Django 6.0.2 on 2026-09-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/', verbose_name='Фото произведения (загрузка с диска)'),
        ),
    ]
