# Generated by Django 6.0.2 on 2026-09-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_artwork_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='price',
            field=models.CharField(default='По запросу', help_text='Например: 150000 или 350 000 ₽ (знак ₽ и пробелы подставляются автоматически)', max_length=100, verbose_name='Стоимость'),
        ),
    ]
