# Generated by Django 6.0.2 on 2026-09-26 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название направления')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Слаг URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Категория материалов',
                'verbose_name_plural': 'Категории материалов',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DecorativeMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название покрытия / материала')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Слаг URL')),
                ('badge', models.CharField(blank=True, help_text='Например: Популярный выбор, Влагостойкий, Авторский арт, Скульптурный рельеф', max_length=100, verbose_name='Бейдж на карточке')),
                ('price_per_sqm', models.PositiveIntegerField(default=4500, help_text='Базовая расчетная стоимость (материал + нанесение мастерами)', verbose_name='Цена за м² под ключ (₽)')),
                ('material_cost_ratio', models.FloatField(default=0.35, help_text='0.35 = 35% на закупку и колеровку состава, 65% на работу декораторов', verbose_name='Доля материалов в смете')),
                ('speed_sqm_per_day', models.PositiveIntegerField(default=20, help_text='Используется для ориентировочного расчета рабочих дней', verbose_name='Скорость нанесения (м² в день)')),
                ('short_desc', models.TextField(help_text='1-2 емких предложения о текстуре и эстетике', verbose_name='Краткое описание (для калькулятора и карточки)')),
                ('full_desc', models.TextField(blank=True, help_text='Детальная экспликация техники нанесения, компонентов и визуального восприятия', verbose_name='Подробное описание и технология')),
                ('composition', models.CharField(blank=True, default='Минеральные компоненты, натуральные пигменты', help_text='Например: Гидравлическая известь, мраморная мука, гранитная крошка', max_length=255, verbose_name='Основа / Состав')),
                ('application_areas', models.CharField(blank=True, default='Гостиные, холлы, спальни, коммерческие пространства', help_text='Например: Санузлы, влажные зоны, фасады, акцентные стены в лобби', max_length=255, verbose_name='Зоны применения')),
                ('fire_rating', models.CharField(default='КМ-0 (негорючий минеральный состав)', max_length=100, verbose_name='Класс пожарной безопасности')),
                ('moisture_resistance', models.CharField(default='Влагостойкое, моющееся покрытие', max_length=150, verbose_name='Стойкость к влаге и уход')),
                ('image', models.ImageField(blank=True, null=True, upload_to='materials/', verbose_name='Главное фото выкраса / текстуры')),
                ('image_url', models.CharField(default='/static/images/hero.jpg', max_length=255, verbose_name='Резервный путь к изображению')),
                ('show_in_calculator', models.BooleanField(default=True, help_text='Если включено, покрытие выводится в сетке выбора калькулятора', verbose_name='Отображать в калькуляторе на главной')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно (показывать на сайте)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='materials.materialcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Декоративное покрытие',
                'verbose_name_plural': 'Каталог материалов & Калькулятор',
                'ordering': ['order', 'price_per_sqm'],
            },
        ),
        migrations.CreateModel(
            name='MaterialSampleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='materials/samples/', verbose_name='Фото образца / интерьера')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Подпись / объект')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='materials.decorativematerial', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Фотография образца',
                'verbose_name_plural': 'Галерея выкрасов и объектов',
                'ordering': ['order', 'id'],
            },
        ),
    ]
