# Generated by Django 6.0.2 on 2026-09-28 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_homepageconfig_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageconfig',
            name='hero_eyebrow',
            field=models.CharField(default='Golden Brush Studio', max_length=200, verbose_name='Hero: Надстрочник'),
        ),
        migrations.AlterField(
            model_name='homepageconfig',
            name='process_badge',
            field=models.CharField(default='Мастерская Golden Brush Studio', max_length=150, verbose_name='Процесс: Подпись на бейдже'),
        ),
    ]
