# Generated by Django 6.0.2 on 2026-10-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_homepageconfig_hero_eyebrow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageconfig',
            name='hero_eyebrow',
            field=models.CharField(blank=True, default='Ателье монументально-декоративного искусства', max_length=200, verbose_name='Hero: Надстрочник'),
        ),
    ]
