# Generated by Django 6.0.2 on 2026-10-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_homepageconfig_hero_eyebrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageconfig',
            name='yandex_metrika_id',
            field=models.CharField(blank=True, default='', help_text='Например: 99123456. При указании счетчик и цели аналитики подключаются автоматически.', max_length=50, verbose_name='Номер счетчика Яндекс.Метрики'),
        ),
    ]
