# Generated by Django 6.0.2 on 2026-10-03 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_homepageconfig_yandex_metrika_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageconfig',
            name='yandex_metrika_id',
            field=models.CharField(blank=True, default='', help_text='Например: 99123456. При указании счетчик и цели аналитики подключаются автоматически.', max_length=50, validators=[django.core.validators.RegexValidator(message='Номер счетчика Яндекс.Метрики должен содержать только цифры (от 5 до 15 знаков).', regex='^\\d{5,15}$')], verbose_name='Номер счетчика Яндекс.Метрики'),
        ),
    ]
