# Generated by Django 6.0.2 on 2026-10-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_homepageconfig_yandex_metrika_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageconfig',
            name='hero_eyebrow',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Hero: Надстрочник'),
        ),
        migrations.AlterField(
            model_name='homepageconfig',
            name='portal1_img_url',
            field=models.CharField(default='/static/images/case_bar_coyote.jpg', max_length=255, verbose_name='Портал 1: Фото'),
        ),
        migrations.AlterField(
            model_name='homepageconfig',
            name='portal2_img_url',
            field=models.CharField(default='/static/images/mat_mural.jpg', max_length=255, verbose_name='Портал 2: Фото'),
        ),
        migrations.AlterField(
            model_name='homepageconfig',
            name='portal2_link',
            field=models.CharField(default='/materials/', max_length=200, verbose_name='Портал 2: Ссылка'),
        ),
        migrations.AlterField(
            model_name='homepageconfig',
            name='portal2_title',
            field=models.CharField(default='Декоративные покрытия и роспись стен', max_length=150, verbose_name='Портал 2: Заголовок'),
        ),
        migrations.AlterField(
            model_name='homepageconfig',
            name='portal3_title',
            field=models.CharField(default='Арт-галерея', max_length=150, verbose_name='Портал 3: Заголовок'),
        ),
    ]
