# Generated by Django 6.0.2 on 2026-10-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_homepageconfig_hero_eyebrow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageconfig',
            name='portal2_title',
            field=models.CharField(default='Декоративные покрытия', max_length=150, verbose_name='Портал 2: Заголовок'),
        ),
    ]
